apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-dotnet-dev
  namespace: kubernetes-cluster-ravindrakumar
  labels:
    app: nagp-dotnet-dev
spec:
  template:
    metadata:
      labels:
        app: nagp-dotnet-dev
        type: develop
    spec:
      containers:
      - name: nagp-dotnet-dev
        image: ravindrahbtik11/i-ravindrakumar-develop-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:  
        - name: DEVOPS_USER_NAME  
          valueFrom:  
            configMapKeyRef:  
              name: dotnet-develop-config  
              key: username  
        - name: DEVOPS_USER_ENV  
          valueFrom:  
            configMapKeyRef:  
              name: dotnet-develop-config  
              key: environment
        - name: DEVOPS_USER_ID  
          valueFrom:  
            secretKeyRef:  
              name: dotnet-develop-secret  
              key: userid  
        - name: DEVOPS_USER_PASS  
          valueFrom:  
            secretKeyRef:  
              name: dotnet-develop-secret  
              key: password              
  replicas: 4
  selector:
    matchLabels:
      app: nagp-dotnet-dev
      type: develop
        
        
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nagp-dotnet-dev
  name: nagp-dotnet-dev
  namespace: kubernetes-cluster-ravindrakumar
spec:
  ports:
  - nodePort: 31110
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nagp-dotnet-dev
    type: develop
  sessionAffinity: None
  type: LoadBalancer

      
      
      
      
      
  
