apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-dotnet-prod
  namespace: kubernetes-cluster-ravindrakumar
  labels:
    app: nagp-dotnet-prod
spec:
  template:
    metadata:
      labels:
        app: nagp-dotnet-prod
        type: master
    spec:
      containers:
      - name: nagp-dotnet-prod
        image: ravindrahbtik11/i-ravindrakumar-master:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:  
        - name: DEVOPS_USER_NAME  
          valueFrom:  
            configMapKeyRef:  
              name: dotnet-master-config  
              key: username
        - name: DEVOPS_USER_ENV  
          valueFrom:  
            configMapKeyRef:  
              name: dotnet-master-config  
              key: environment
        - name: DEVOPS_USER_ID  
          valueFrom:  
            secretKeyRef:  
              name: dotnet-master-secret  
              key: userid  
        - name: DEVOPS_USER_PASS  
          valueFrom:  
            secretKeyRef:  
              name: dotnet-master-secret  
              key: password                           
  replicas: 4
  selector:
    matchLabels:
      app: nagp-dotnet-prod
      type: master
        
        
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nagp-dotnet-prod
  name: nagp-dotnet-prod
  namespace: kubernetes-cluster-ravindrakumar
spec:
  ports:
  - nodePort: 32567
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nagp-dotnet-prod
    type: master
  sessionAffinity: None
  type: LoadBalancer

      
      
      
      
      
  
